# Generated by Django 3.2.10 on 2022-02-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
                ('mileage', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
