# Generated by Django 3.2.10 on 2022-02-01 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcarapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='car',
            name='unit',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
